#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio for Nijanth Anand to publish his work on Data and Analytics'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-nijanthanand-github-io-analytics'

#-------------------------------
# About Section

about: >
  # Nijanth Anand

  This is Nijanth Anand, an aspiring Data Analyst. Having worked in Business Intelligence and Business Operations for a while, I decided to pursue a Masters in Business Analytics at the Paul Merage School of Business, UC Irvine.  
  

  You may contact me [through my email](mailto:nijantha@uci.edu) or [tweet at me](https://twitter.com/TheNijanthAnand) if you have any questions or would like to ask me about anything. 
#-------------------------------
# Work Section

projects:
- {name: 'Spotify Chartbuster prediction', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Impact of Freemium Business Model', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Geo Fencing', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Apriori Alogirthms on Restaurant Cuisines', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Twitter Sentiment Analsyis', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/TheNijanthAnand'}
- {icon: 'github', link: 'https://github.com/nijanthanand'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/nijanth-anand/'}
- {icon: 'envelope', link: 'mailto:nijantha@uci.edu'}

# social network icons available: 'twitter' /  'github' /  'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
